version: "3.7"
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: users_db
      MYSQL_ROOT_PASSWORD: toor
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ./internal/mysql-db:/var/lib/mysql
    networks:
      - starnet

  starcloud-api:
    build: .
    depends_on:
      - phpmyadmin
    ports:
      - "8090:8080"
    links:
      - "db:database"
    networks:
      - starnet

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: toor
    networks:
      - starnet

  # Prometheus
  prometheus:
    build: ./deployments/prometheus
    ports:
    - "9090:9090"
    networks:
      - starnet
    depends_on:
      - starcloud-api

  # Grafana
  grafana:
    build: ./deployments/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./internal/grafana-data:/var/lib/grafana
    networks:
      - starnet
    depends_on:
      - prometheus



networks:
  starnet:


